---
title: "Module 9 Homework"
author: "Yanhe Wen"
output:
  pdf_document: default
  html_notebook: default
---

##Question 1
```{r warning=FALSE, message=FALSE}
library(multtest)
data("golub")
```
###(a)
```{r}
GRO2 <- golub[grep("GRO2 GRO2",golub.gnames[,2]),]
GRO3 <- golub[grep("GRO3 GRO3",golub.gnames[,2]),]
cat("The correlation is:",cor(GRO2,GRO3))
```

###(b)
```{r}
cor.test(GRO2,GRO3, conf.level = 0.9)
cat("The 90% CI is: (0.6702984, 0.8780861)")
```

###(c)
```{r}
nboot1 <- 2000
boot1.cor <- matrix(0, nrow = nboot1, ncol = 1)
data1 <- cbind(GRO2,GRO3)
for(i in 1:nboot1){
  dat.star1 <- data1[sample(1:nrow(data1),replace = TRUE),]
  boot1.cor[i,] <- cor(dat.star1[,1],dat.star1[,2])
}
cat("The bootstrap 90% CI:\n")
quantile(boot1.cor[,1],c(0.05,0.95))

```

###(d)
```{r}
cat("We can do the t-test from the bootstrap data, the t-test is showed below: \n")
t.test(boot1.cor, mu = 0.64, alternative = "greater", conf.level = 0.95)
cat("p.value is less than 2.2e-16, so we reject the null hypothesis, the correlations mean
    is greater than 0.64")
```

##Question 2
###(a)
```{r}
zyxin_rowNum <- grep("Zyxin",golub.gnames[,2])
zyxin <- golub[zyxin_rowNum,]
cor2 <- apply(golub,1,function(x) cor(x,zyxin))
cat("There are",sum(cor2 < -0.5),"genes' corrlation values are less than -0.5")
```
###(b)
```{r}
for(i in 1:5){
  cat(golub.gnames[order(cor2,decreasing = FALSE)[i],2],"\n")
}
```

###(c)
```{r}
p_values2 <- apply(golub, 1, function(x) cor.test(x,zyxin,alternative = "less")$p.value)
p_fdrs2 <- p.adjust(p_values2, method = "fdr")
cat("Using the false discovery rae of 0.05, numbers of genes are listed below: \n")
sum(p_fdrs2<0.05)
```

##Question 3
###(a)
```{r}
reg3.fit <- lm(formula = GRO3~GRO2)
summary(reg3.fit)
cat("Yes, there is a significant relationship between the two genes. p.value is 2.20e-09, we 
    reject null hypothesis")
```
###(b)
```{r}
confint(reg3.fit, level = 0.95)
cat("Yes, the slope is less than 0.5, since 95% CI is from 0.266 to 0.450")
```
###(c)
```{r}
predict(reg3.fit, newdata = data.frame(GRO2=0), interval = "prediction", level = 0.8)
cat("The 80% PI is: (-1.267563,-0.4175553)")
```
###(d)
```{r}
qqnorm(resid(reg3.fit))
qqline(resid(reg3.fit))
shapiro.test(resid(reg3.fit))
cat("From the plot and the results from shapiro test, we can tell the residuals are normally
    distributed, plus the p.value is greater than 0.05, we accept the null hypothesis, which 
    agrees with the normality")
```

##Question 4
###(a)
```{r}
data("stackloss")
attach(stackloss)
lin_reg4 <- lm(stack.loss ~ Air.Flow + Water.Temp + Acid.Conc.)
summary(lin_reg4)
cat("stackloss = 0.7156*Air.Flow + 1.2953*Water.Temp - 0.1521*Acid.Conc")
```
###(b)
```{r}
cat("Air.Flow and Water.Temp are significant effect on stackloss, Acid.Conc is not. 
    91.36% of variation ")
```
###(c)
```{r}
predict(lin_reg4, data.frame(Air.Flow=60, Water.Temp=20, Acid.Conc.=90), 
        interval = "confidence", level = 0.9)
cat("The 90% CI is (13.50069, 16.96617)")
predict(lin_reg4, data.frame(Air.Flow=60, Water.Temp=20, Acid.Conc.=90), 
        interval = "prediction", level = 0.9)
cat("The 90% PI is (9.331184, 21.13568)")
```